config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'books/:id/delete', to: 'books#delete', as: 'delete_book'
  root 'books#index'
  resources :books
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    # GET /books
    # This action will show all books in your collection
    def index
      @books = Book.all
    end
  
    # GET /books/new
    # This action will show a form to add a new book
    def new
      @book = Book.new
    end
  
    # POST /books
    # This action will handle the form submission from the 'new' action
    # and will create a new book in the database
    def create
      @book = Book.new(book_params)
      if @book.save
        flash[:success] = "Book was successfully created."
        redirect_to @book
      else
        render :new
      end
    end
  
    # GET /books/:id/edit
    # This action will show a form to edit an existing book
    def edit
      @book = Book.find(params[:id])
    end
  
    # PATCH/PUT /books/:id
    # This action will handle the form submission from the 'edit' action
    # and will update the book in the database
    def update
      @book = Book.find(params[:id])
      if @book.update(book_params)
        flash[:success] = "Book was successfully updated."
        redirect_to @book
      else
        render :edit
      end
    end
  
    # GET /books/:id
    # This action will show the details of a single book
    def show
      @book = Book.find(params[:id])
    end
  
    def delete
        @book = Book.find(params[:id])
    end

    # DELETE /books/:id
    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        flash[:success] = "Book was successfully deleted."
        redirect_to books_url
    end
  
    private
      # Use callbacks to share common setup or constraints between actions
      def set_book
        @book = Book.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through
      def book_params
        params.require(:book).permit(:title, :author, :price, :published_date)
      end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/delete.html.erb
<!-- In app/views/books/delete.html.erb -->

<h1>Delete Book</h1>

<p>Are you sure you want to delete "<%= @book.title %>"?</p>

<%= link_to 'Confirm Delete', book_path(@book), method: :delete, data: { confirm: 'Are you really sure?' }, class: "button" %>

<%= link_to 'Cancel', book_path(@book), class: "button" %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= form_with(model: @book, local: true) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :book_title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, step: 0.01 %>
  </div>

  <div class="field">
    <%= form.label :published_date, 'Published Date' %>
    <%= form.date_field :published_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back to Books', books_path %>

app/views/books/index.html.erb
<h1>All Books</h1>

<%= link_to 'Add New Book', new_book_path %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td>
          <%= link_to 'Show', book %>
          <%= link_to 'Edit', edit_book_path(book) %>
          <!-- Update this link to point to the delete confirmation page -->
          <%= link_to 'Delete', delete_book_path(book) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<h1>Add New Book</h1>

<%= form_with(model: @book, local: true) do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :book_title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, step: 0.01 %>
  </div>

  <div class="field">
    <%= form.label :published_date, 'Published Date' %>
    <%= form.date_field :published_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back to Books', books_path %>

app/views/books/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@book.price) %>
</p>

<p>
  <strong>Published Date:</strong>
  <%= @book.published_date %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back to Books', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookCollection</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
 
</head>

<body>
  <% flash.each do |type, message| %>
    <div class="<%= type %>"><%= message %></div>
  <% end %>

  <%= yield %>
</body>
</html>